### ISSUE TITLE
Feedback about the recent centos system cannot install this mtp

### ISSUE THREAD

**Issue by asd307769162** [HirbodBehnam/MTProtoProxyCentOSInstall#54]
I have tried centos7, centos8, and centos9 respectively, and they all prompt "your os is not support", so I can't install it. This problem didn't exist before, but it appeared recently. Can you check it? Thank you

**Comment by HirbodBehnam** [comment]
Hello
Yes the CentOS support is dropped in the latest version. The reason is that its eol will be reached in 6 months.
If you want, you can use the latest version which supports CentOS 7 and 8 which is [here](https://raw.githubusercontent.com/HirbodBehnam/MTProtoProxyInstaller/4dfad402915ee612332a171c919dcd90132de643/MTProtoProxyInstall.sh).
Just download the script on your server and run it with bash!
